Ohos 1570 page number should not be mandatory in api
OurHeritageOurStories/ohos-neptune-ec2-api pull request #41
Opened 2023-04-24 12:49 UTC by AndrewBewseyTNA

Instead of defaulting to "you must provide both parms", we now check in more detail what you've provided:

- If its nothing, then you get a message telling you to provide both params
- If you provide a page only, then you get a message saying you need to provide a search term
- If you provide provide a search term only, then the default page value of "1" is used
- If you provide both, then both are used

This also means an update to the docs - as page is no longer required, then becomes a "false"

2023-04-26 10:01 UTC, AndrewBewseyTNA commented
Closed as will be superceded by https://national-archives.atlassian.net/jira/software/projects/OHOS/boards/82/backlog?selectedIssue=OHOS-1571 and https://national-archives.atlassian.net/jira/software/projects/OHOS/boards/82/backlog?selectedIssue=OHOS-1553

2023-04-27 10:28 UTC, AndrewBewseyTNA commented
Reopened on request of Hazel

2023-05-02 08:59 UTC, hgupta-tna approved these changes

2023-05-02 09:53 UTC, bogden1 approved these changes
My instinct for the error message would be to either to say that page number is optional, or else not mention it at all. But if its the way it is for a reason then this looks good to me.

I don't see anything about ensuring consistency of parameters, but happy to believe that parameters are set up in a consistent order.

Are there any unit tests to update?

Approving on the assumption that my questions don't apply/have good answers.

2023-05-02 10:03 UTC, mark-bell-tna commented
@hgupta-tna @AndrewBewseyTNA 
Now that we have Bernard on board too, could we talk again about writing some guidelines for the code review process? Could you arrange a one hour meeting between the four of us for next week to talk through the process? The meeting doesn't have to be in person, Teams will be fine. Then we can add a task into the next sprint to write up the guidelines. Thanks, Mark

2023-05-02 10:08 UTC, mark-bell-tna requested changes
Instead of using len(userProvidedParams) can you use the two boolean variables you already have?
If qPresent {
     if pagePresent {
           use page
     } else {
           page = 1
     } 
 } else {
       return no search parameter error;
}

The no search parameter error should mention that page number is optional and defaults to 1
}

2023-05-04 14:55 UTC, AndrewBewseyTNA commented
Closed, covered by #42, which incorporated fixes for this bug, partly by adjusting the behavior of queryparam defaults.

2023-05-04 14:55 UTC, closed without merging